// <auto-generated />
using System;
using ImportacaoPreco.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImportacaoPreco.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190801201741_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Cor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int?>("ProdutoId");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Cores");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("ValorBase");

                    b.HasKey("Id");

                    b.ToTable("Precos");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int?>("PrecoId");

                    b.Property<int?>("SubgrupoId");

                    b.HasKey("Id");

                    b.HasIndex("PrecoId");

                    b.HasIndex("SubgrupoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Subgrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GrupoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Subgrupos");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Cor", b =>
                {
                    b.HasOne("ImportacaoPreco.Dominio.Entities.Produto")
                        .WithMany("Cores")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Preco", b =>
                {
                    b.OwnsMany("ImportacaoPreco.Dominio.VO.PrecoPromocional", "PrecosPromocionais", b1 =>
                        {
                            b1.Property<decimal>("Valor");

                            b1.Property<DateTime>("DataInicioPromocao");

                            b1.Property<DateTime>("DataFimPromocao");

                            b1.Property<int>("PrecoId");

                            b1.HasKey("Valor", "DataInicioPromocao", "DataFimPromocao");

                            b1.HasIndex("PrecoId");

                            b1.ToTable("PrecoPromocional");

                            b1.HasOne("ImportacaoPreco.Dominio.Entities.Preco")
                                .WithMany("PrecosPromocionais")
                                .HasForeignKey("PrecoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Produto", b =>
                {
                    b.HasOne("ImportacaoPreco.Dominio.Entities.Preco", "Preco")
                        .WithMany()
                        .HasForeignKey("PrecoId");

                    b.HasOne("ImportacaoPreco.Dominio.Entities.Subgrupo", "Subgrupo")
                        .WithMany()
                        .HasForeignKey("SubgrupoId");

                    b.OwnsMany("ImportacaoPreco.Dominio.ValueObjects.Tamanho", "Tamanhos", b1 =>
                        {
                            b1.Property<string>("Nome")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("ProdutoId");

                            b1.HasKey("Nome");

                            b1.HasIndex("ProdutoId");

                            b1.ToTable("Tamanho");

                            b1.HasOne("ImportacaoPreco.Dominio.Entities.Produto")
                                .WithMany("Tamanhos")
                                .HasForeignKey("ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("ImportacaoPreco.Dominio.Entities.Subgrupo", b =>
                {
                    b.HasOne("ImportacaoPreco.Dominio.Entities.Grupo", "Grupo")
                        .WithMany("Subgrupo")
                        .HasForeignKey("GrupoId");
                });
#pragma warning restore 612, 618
        }
    }
}
